# Generated by Django 5.1.3 on 2026-04-30 13:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Gider Başlığı"),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("elektrik", "Elektrik Faturası"),
                            ("su", "Su Faturası"),
                            ("dogalgaz", "Doğalgaz Faturası"),
                            ("kira", "Depo/Ofis Kirası"),
                            ("personel", "Personel Maaş/Yevmiye"),
                            ("bakim", "Makine Bakım/Onarım"),
                            ("diger", "Diğer İşletme Giderleri"),
                        ],
                        max_length=20,
                        verbose_name="Gider Kategorisi",
                    ),
                ),
                (
                    "miktar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar (₺)"
                    ),
                ),
                (
                    "tarih",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Harcama Tarihi"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
            ],
            options={
                "verbose_name": "İşletme Gideri",
                "verbose_name_plural": "İşletme Giderleri",
                "ordering": ["-tarih"],
            },
        ),
        migrations.CreateModel(
            name="Mustahsil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_soyad",
                    models.CharField(max_length=200, verbose_name="Üretici Ad Soyad"),
                ),
                (
                    "tc_no",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="TC Kimlik No",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefon"
                    ),
                ),
                ("bolge", models.CharField(max_length=100, verbose_name="Bölge/Köy")),
                (
                    "toplam_borc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Güncel Borcumuz (₺)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müstahsil (Üretici)",
                "verbose_name_plural": "Müstahsiller",
                "ordering": ["ad_soyad"],
            },
        ),
        migrations.CreateModel(
            name="Musteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unvan",
                    models.CharField(
                        max_length=255, verbose_name="Müşteri Ünvanı / Ad Soyad"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "bolge",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bölge/Şehir",
                    ),
                ),
                (
                    "toplam_alacagimiz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Güncel Alacak (₺)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri (Alıcı)",
                "verbose_name_plural": "Müşteriler",
                "ordering": ["unvan"],
            },
        ),
        migrations.CreateModel(
            name="CariHareket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "islem_tipi",
                    models.CharField(
                        choices=[
                            ("alimgiris", "Mal Alım Girişi (Borçlanırız)"),
                            ("odeme", "Ödeme Yapıldı (Borç Azalır)"),
                            ("fason_hizmet", "Fason Hizmet Bedeli (Alacaklanırız)"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "miktar",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tutar (₺)"
                    ),
                ),
                (
                    "tarih",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True, null=True, verbose_name="Not/Açıklama"
                    ),
                ),
                (
                    "mustahsil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hareketler",
                        to="finance.mustahsil",
                        verbose_name="Müstahsil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Hareket",
                "verbose_name_plural": "Cari Hareketler",
                "ordering": ["-tarih", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Sevkiyat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaka", models.CharField(max_length=20, verbose_name="Araç Plakası")),
                (
                    "sofor_ad",
                    models.CharField(max_length=100, verbose_name="Şoför Ad Soyad"),
                ),
                (
                    "cikis_tarihi",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Çıkış Tarihi"
                    ),
                ),
                (
                    "tamamlandi",
                    models.BooleanField(
                        default=False, verbose_name="Teslimat Tamamlandı"
                    ),
                ),
                (
                    "satis_birim_fiyat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Satış Birim Fiyat (KG/₺)",
                    ),
                ),
                (
                    "toplam_satis_tutari",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                        verbose_name="Toplam Satış Tutarı (₺)",
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sevkiyatlar",
                        to="finance.musteri",
                        verbose_name="Alıcı Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sevkiyat / Tır",
                "verbose_name_plural": "Sevkiyatlar ve Tırlar",
                "ordering": ["-cikis_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="MusteriHareket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "islem_tipi",
                    models.CharField(
                        choices=[
                            ("satis", "Satış / Alacak Ekle"),
                            ("tahsilat", "Tahsilat / Ödeme Alındı"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "miktar",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tutar (₺)"
                    ),
                ),
                (
                    "tarih",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "odendi_mi",
                    models.BooleanField(
                        default=False, verbose_name="Ödeme Kapandı/Ödendi"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True, null=True, verbose_name="Not/Açıklama"
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hareketler",
                        to="finance.musteri",
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "sevkiyat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.sevkiyat",
                        verbose_name="İlgili Tır/Plaka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Hareketi",
                "verbose_name_plural": "Müşteri Hareketleri",
                "ordering": ["-tarih", "-id"],
            },
        ),
    ]
