# Generated by Django 5.2.12 on 2026-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=50, unique=True, verbose_name='Fatura No')),
                ('musteri_adi', models.CharField(max_length=200, verbose_name='Müşteri/Kurum Adı')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Tutar (₺)')),
                ('durum', models.CharField(choices=[('odendi', 'Ödendi'), ('bekliyor', 'Ödeme Bekliyor'), ('iptal', 'İptal Edildi')], default='bekliyor', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('fatura_dosyası', models.FileField(blank=True, null=True, upload_to='fatura_arsivi/', verbose_name='Resmi Fatura Dosyası')),
            ],
        ),
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Gider Başlığı')),
                ('kategori', models.CharField(choices=[('maas', 'Personel Maaşı'), ('yakit', 'Yakıt/Lojistik'), ('hammadde', 'Hammadde/Tohum'), ('fatura', 'Kira/Elektrik/Su'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('tarih', models.DateField(verbose_name='Harcama Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('belge', models.FileField(blank=True, null=True, upload_to='gider_belgeleri/', verbose_name='Fatura/Fiş Görseli')),
            ],
        ),
    ]
