# Generated by Django 5.2.12 on 2026-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='fatura_dosyası',
        ),
        migrations.RemoveField(
            model_name='gider',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='gider',
            name='belge',
        ),
        migrations.AlterField(
            model_name='fatura',
            name='durum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='fatura_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='musteri_adi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gider',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gider',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gider',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gider',
            name='tarih',
            field=models.DateField(),
        ),
    ]
