# Generated by Django 5.2.12 on 2026-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_fatura_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama (Diğer Seçilirse Burayı Doldurun)'),
        ),
        migrations.AddField(
            model_name='gider',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama/Detay'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='durum',
            field=models.CharField(choices=[('odendi', 'Ödendi'), ('bekliyor', 'Ödeme Bekliyor'), ('iptal', 'İptal Edildi'), ('diger', 'Diğer')], default='bekliyor', max_length=20, verbose_name='Ödeme Durumu'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='fatura_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Fatura No'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='musteri_adi',
            field=models.CharField(max_length=200, verbose_name='Müşteri/Kurum Adı'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Tutar (₺)'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Gider Başlığı'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='kategori',
            field=models.CharField(choices=[('maas', 'Personel Maaşı'), ('yakit', 'Yakıt/Lojistik'), ('hammadde', 'Hammadde/Tohum'), ('fatura', 'Kira/Elektrik/Su'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='tarih',
            field=models.DateField(verbose_name='Harcama Tarihi'),
        ),
    ]
