# Generated by Django 5.2.12 on 2026-04-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_fatura_aciklama_gider_aciklama_alter_fatura_durum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mustahsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Üretici Ad Soyad')),
                ('tc_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('bolge', models.CharField(max_length=100, verbose_name='Bölge/Köy')),
                ('toplam_borc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Güncel Borcumuz (₺)')),
            ],
            options={
                'verbose_name': 'Müstahsil (Üretici)',
                'verbose_name_plural': 'Müstahsiller',
            },
        ),
        migrations.CreateModel(
            name='CariHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('alimgiris', 'Mal Alım Girişi (Borçlanırız)'), ('odeme', 'Ödeme Yapıldı (Borç Azalır)')], max_length=20, verbose_name='İşlem Tipi')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Not/Açıklama')),
                ('mustahsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='finance.mustahsil', verbose_name='Müstahsil')),
            ],
            options={
                'verbose_name': 'Cari Hareket',
                'verbose_name_plural': 'Cari Hareketler',
            },
        ),
    ]
