# Generated by Django 5.2.12 on 2026-04-04 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_mustahsil_carihareket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carihareket',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi'),
        ),
    ]
