# Generated by Django 5.2.12 on 2026-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_carihareket_tarih'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturalar'},
        ),
        migrations.AlterModelOptions(
            name='gider',
            options={'verbose_name': 'Gider', 'verbose_name_plural': 'Giderler'},
        ),
        migrations.AlterField(
            model_name='fatura',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
