# Generated by Django 5.2.12 on 2026-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_fatura_options_alter_gider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carihareket',
            name='islem_tipi',
            field=models.CharField(choices=[('alimgiris', 'Mal Alım Girişi (Borçlanırız)'), ('odeme', 'Ödeme Yapıldı (Borç Azalır)'), ('fason_hizmet', 'Fason Hizmet Bedeli (Alacaklanırız)')], max_length=20, verbose_name='İşlem Tipi'),
        ),
    ]
