# Generated by Django 5.2.12 on 2026-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_carihareket_islem_tipi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
