# Generated by Django 5.2.12 on 2026-04-04 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_fatura_aciklama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gider',
            options={'verbose_name': 'İşletme Gideri', 'verbose_name_plural': 'İşletme Giderleri'},
        ),
        migrations.AlterField(
            model_name='gider',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Gider Başlığı (Örn: Mart Ayı Kirası)'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='kategori',
            field=models.CharField(choices=[('elektrik', 'Elektrik Faturası'), ('su', 'Su Faturası'), ('dogalgaz', 'Doğalgaz Faturası'), ('kira', 'Depo/Ofis Kirası'), ('personel', 'Personel Maaş/Yevmiye'), ('bakim', 'Makine Bakım/Onarım'), ('diger', 'Diğer İşletme Giderleri')], max_length=20, verbose_name='Gider Kategorisi'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Harcama Tarihi'),
        ),
    ]
