# Generated by Django 5.2.12 on 2026-04-04 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_gider_options_alter_gider_baslik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sevkiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, verbose_name='Araç Plakası')),
                ('sofor_ad', models.CharField(max_length=100, verbose_name='Şoför Ad Soyad')),
                ('gidecegi_yer', models.CharField(max_length=200, verbose_name='Varış Noktası')),
                ('cikis_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Çıkış Tarihi')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Teslimat Tamamlandı')),
                ('satis_birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Satış Birim Fiyat (KG/₺)')),
                ('toplam_satis_tutari', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Toplam Satış Tutarı (₺)')),
            ],
            options={
                'verbose_name': 'Sevkiyat / Tır',
                'verbose_name_plural': 'Sevkiyatlar ve Tırlar',
            },
        ),
        migrations.DeleteModel(
            name='Fatura',
        ),
        migrations.AlterField(
            model_name='gider',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Gider Başlığı'),
        ),
    ]
