# Generated by Django 5.2.12 on 2026-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_sevkiyat_delete_fatura_alter_gider_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carihareket',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar (₺)'),
        ),
        migrations.AlterField(
            model_name='mustahsil',
            name='toplam_borc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Güncel Borcumuz (₺)'),
        ),
        migrations.AlterField(
            model_name='sevkiyat',
            name='toplam_satis_tutari',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Toplam Satış Tutarı (₺)'),
        ),
    ]
