# Generated by Django 5.2.12 on 2026-04-05 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_carihareket_miktar_alter_mustahsil_toplam_borc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(max_length=255, verbose_name='Müşteri Ünvanı / Ad Soyad')),
                ('vergi_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='Vergi/TC No')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('toplam_alacagimiz', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Güncel Alacağımız (₺)')),
            ],
            options={
                'verbose_name': 'Müşteri (Alıcı)',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='MusteriHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('satis', 'Tır Satış Kaydı (Alacaklanırız)'), ('tahsilat', 'Ödeme Alındı (Alacak Azalır)')], max_length=20, verbose_name='İşlem Tipi')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar (₺)')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Not/Açıklama')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='finance.musteri', verbose_name='Müşteri')),
                ('sevkiyat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.sevkiyat', verbose_name='İlgili Sevkiyat Plakası')),
            ],
            options={
                'verbose_name': 'Müşteri Hareketi',
                'verbose_name_plural': 'Müşteri Hareketleri',
            },
        ),
    ]
