# Generated by Django 5.2.12 on 2026-04-05 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_musteri_musterihareket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteri',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='vergi_no',
        ),
        migrations.AddField(
            model_name='musteri',
            name='bolge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölge/Şehir'),
        ),
        migrations.AddField(
            model_name='musterihareket',
            name='odendi_mi',
            field=models.BooleanField(default=False, verbose_name='Ödeme Kapandı/Ödendi'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='toplam_alacagimiz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Güncel Alacak (₺)'),
        ),
        migrations.AlterField(
            model_name='musterihareket',
            name='islem_tipi',
            field=models.CharField(choices=[('satis', 'Satış / Alacak Ekle'), ('tahsilat', 'Tahsilat / Ödeme Alındı')], max_length=20, verbose_name='İşlem Tipi'),
        ),
        migrations.AlterField(
            model_name='musterihareket',
            name='sevkiyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.sevkiyat', verbose_name='İlgili Tır/Plaka'),
        ),
        migrations.AlterField(
            model_name='musterihareket',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
    ]
