# Generated by Django 5.2.12 on 2026-04-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_musteri_adres_remove_musteri_vergi_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sevkiyat',
            name='gidecegi_yer',
        ),
        migrations.AddField(
            model_name='sevkiyat',
            name='musteri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sevkiyatlar', to='finance.musteri', verbose_name='Alıcı Müşteri'),
        ),
    ]
