# Generated by Django 5.2.12 on 2026-04-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_sevkiyat_gidecegi_yer_sevkiyat_musteri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carihareket',
            options={'ordering': ['-tarih', '-id'], 'verbose_name': 'Cari Hareket', 'verbose_name_plural': 'Cari Hareketler'},
        ),
        migrations.AlterModelOptions(
            name='gider',
            options={'ordering': ['-tarih'], 'verbose_name': 'İşletme Gideri', 'verbose_name_plural': 'İşletme Giderleri'},
        ),
        migrations.AlterModelOptions(
            name='mustahsil',
            options={'ordering': ['ad_soyad'], 'verbose_name': 'Müstahsil (Üretici)', 'verbose_name_plural': 'Müstahsiller'},
        ),
        migrations.AlterModelOptions(
            name='musteri',
            options={'ordering': ['unvan'], 'verbose_name': 'Müşteri (Alıcı)', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='musterihareket',
            options={'ordering': ['-tarih', '-id'], 'verbose_name': 'Müşteri Hareketi', 'verbose_name_plural': 'Müşteri Hareketleri'},
        ),
        migrations.AlterModelOptions(
            name='sevkiyat',
            options={'ordering': ['-cikis_tarihi'], 'verbose_name': 'Sevkiyat / Tır', 'verbose_name_plural': 'Sevkiyatlar ve Tırlar'},
        ),
    ]
