# Generated by Django 5.1.3 on 2026-04-30 13:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Depo/Oda Adı")),
                (
                    "kapasite_palet",
                    models.IntegerField(verbose_name="Palet Kapasitesi"),
                ),
                (
                    "sicaklik",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="İdeal Sıcaklık",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depo/Oda",
                "verbose_name_plural": "Depolar ve Odalar",
            },
        ),
        migrations.CreateModel(
            name="UrunKategorisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=100, verbose_name="Ürün Cinsi (Örn: Elma)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Cinsi",
                "verbose_name_plural": "Ürün Cinsleri",
            },
        ),
        migrations.CreateModel(
            name="Palet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toplam_palet_adedi",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="İşleme sonucu çıkan palet sayısı",
                        verbose_name="Toplam Palet Adedi",
                    ),
                ),
                (
                    "palet_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Palet ID / Barkod (Boş bırakılabilir)",
                    ),
                ),
                (
                    "urun_fotografi",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="palet_fotos/%Y/%m/%d/",
                        verbose_name="Ürün Fotoğrafı (Kalite Kontrol)",
                    ),
                ),
                (
                    "mulkiyet_tipi",
                    models.CharField(
                        choices=[
                            ("oz_mal", "Greennova Öz Malı"),
                            ("fason", "Fason Müşteri Malı"),
                        ],
                        default="oz_mal",
                        max_length=20,
                        verbose_name="Mülkiyet",
                    ),
                ),
                (
                    "brut_miktar_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Kantar Giriş (Brüt KG)",
                    ),
                ),
                (
                    "miktar_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Paketlenen / Stok (Net KG)",
                    ),
                ),
                (
                    "fire_miktar_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                        verbose_name="İşleme Farkı (Fire/Çıkma)",
                    ),
                ),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Birim Fiyat (₺)",
                    ),
                ),
                (
                    "toplam_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=12,
                        verbose_name="Toplam Tutar (Ödemeye Esas)",
                    ),
                ),
                (
                    "giris_tarihi",
                    models.DateField(
                        auto_now_add=True, verbose_name="Depoya Giriş Tarihi"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("depoda", "Depoda Bekliyor"),
                            ("isleniyor", "İşleniyor/Paketlemede"),
                            ("yuklendi", "Tıra Yüklendi"),
                            ("sevk", "Sevkiyatta/Yolda"),
                            ("cikti", "Teslim Edildi"),
                        ],
                        default="isleniyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "isleme_notu",
                    models.TextField(
                        blank=True, null=True, verbose_name="İşleme/Fason Notu"
                    ),
                ),
                (
                    "qr_kod",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR Kod",
                    ),
                ),
                (
                    "depo_konumu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.depo",
                        verbose_name="Bulunduğu Oda",
                    ),
                ),
                (
                    "mustahsil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.mustahsil",
                        verbose_name="Sahibi",
                    ),
                ),
                (
                    "sevkiyat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paletler",
                        to="finance.sevkiyat",
                        verbose_name="Yüklendiği Tır",
                    ),
                ),
                (
                    "urun_cinsi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.urunkategorisi",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palet Takibi",
                "verbose_name_plural": "Depodaki Paletler",
                "ordering": ["-id"],
            },
        ),
    ]
