# Generated by Django 5.2.12 on 2026-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('kategori', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori')),
                ('stok_miktari', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (₺)')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sisteme Eklenme Tarihi')),
            ],
        ),
    ]
