# Generated by Django 5.2.12 on 2026-04-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_fatura_options_alter_gider_options_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Depo/Oda Adı')),
                ('kapasite_palet', models.IntegerField(verbose_name='Palet Kapasitesi')),
                ('sicaklik', models.CharField(blank=True, max_length=50, null=True, verbose_name='İdeal Sıcaklık')),
            ],
            options={
                'verbose_name': 'Depo/Oda',
                'verbose_name_plural': 'Depolar ve Odalar',
            },
        ),
        migrations.CreateModel(
            name='Palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palet_no', models.CharField(max_length=50, unique=True, verbose_name='Palet ID / Barkod')),
                ('miktar_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar (KG)')),
                ('giris_tarihi', models.DateField(auto_now_add=True, verbose_name='Depoya Giriş Tarihi')),
                ('durum', models.CharField(choices=[('depoda', 'Depoda Bekliyor'), ('sevk', 'Sevkiyatta/Tırda'), ('cikti', 'Depodan Çıktı/Satıldı')], default='depoda', max_length=20, verbose_name='Durum')),
                ('depo_konumu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.depo', verbose_name='Bulunduğu Oda')),
                ('mustahsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.mustahsil', verbose_name='Sahibi (Üretici)')),
            ],
            options={
                'verbose_name': 'Palet Takibi',
                'verbose_name_plural': 'Depodaki Paletler',
            },
        ),
        migrations.CreateModel(
            name='UrunKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ürün Cinsi (Örn: Elma)')),
            ],
            options={
                'verbose_name': 'Ürün Cinsi',
                'verbose_name_plural': 'Ürün Cinsleri',
            },
        ),
        migrations.DeleteModel(
            name='Urun',
        ),
        migrations.AddField(
            model_name='palet',
            name='urun_cinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.urunkategorisi', verbose_name='Ürün'),
        ),
    ]
