# Generated by Django 5.2.12 on 2026-04-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_carihareket_islem_tipi'),
        ('inventory', '0002_depo_palet_urunkategorisi_delete_urun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='isleme_notu',
            field=models.TextField(blank=True, null=True, verbose_name='İşleme/Fason Notu'),
        ),
        migrations.AddField(
            model_name='palet',
            name='mulkiyet_tipi',
            field=models.CharField(choices=[('oz_mal', 'Greennova Öz Malı'), ('fason', 'Fason Müşteri Malı')], default='oz_mal', max_length=20, verbose_name='Mülkiyet'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='durum',
            field=models.CharField(choices=[('depoda', 'Depoda Bekliyor'), ('isleniyor', 'İşleniyor/Paketlemede'), ('sevk', 'Sevkiyatta/Tırda'), ('cikti', 'Depodan Çıktı/Teslim Edildi')], default='depoda', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='mustahsil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.mustahsil', verbose_name='Sahibi (Üretici/Müşteri)'),
        ),
    ]
