# Generated by Django 5.2.12 on 2026-04-04 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_palet_isleme_notu_palet_mulkiyet_tipi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sevkiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, verbose_name='Araç Plakası')),
                ('sofor_ad', models.CharField(max_length=100, verbose_name='Şoför Ad Soyad')),
                ('sofor_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Şoför Telefon')),
                ('gidecegi_yer', models.CharField(max_length=200, verbose_name='Varış Noktası (Hal/Market/Liman)')),
                ('cikis_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Çıkış Tarihi')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Teslimat Tamamlandı mı?')),
            ],
            options={
                'verbose_name': 'Sevkiyat / Tır',
                'verbose_name_plural': 'Sevkiyatlar ve Tırlar',
            },
        ),
        migrations.CreateModel(
            name='SevkiyatPaleti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.palet', verbose_name='Yüklenen Palet')),
                ('sevkiyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuklu_paletler', to='inventory.sevkiyat')),
            ],
        ),
    ]
