# Generated by Django 5.2.12 on 2026-04-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sevkiyat_sevkiyatpaleti'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='qr_kod',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
    ]
