# Generated by Django 5.2.12 on 2026-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_palet_qr_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevkiyat',
            name='gidecegi_yer',
            field=models.CharField(max_length=200, verbose_name='Varış Noktası'),
        ),
    ]
