# Generated by Django 5.2.12 on 2026-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_sevkiyat_gidecegi_yer'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat (₺)'),
        ),
        migrations.AddField(
            model_name='palet',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Toplam Tutar'),
        ),
    ]
