# Generated by Django 5.2.12 on 2026-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_palet_birim_fiyat_palet_toplam_tutar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevkiyat',
            name='satis_birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Satış Birim Fiyat (KG/₺)'),
        ),
        migrations.AddField(
            model_name='sevkiyat',
            name='toplam_satis_tutari',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Toplam Satış Tutarı (₺)'),
        ),
    ]
