# Generated by Django 5.2.12 on 2026-04-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_sevkiyat_delete_fatura_alter_gider_aciklama_and_more'),
        ('inventory', '0008_sevkiyat_satis_birim_fiyat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sevkiyatpaleti',
            name='sevkiyat',
        ),
        migrations.RemoveField(
            model_name='sevkiyatpaleti',
            name='palet',
        ),
        migrations.AddField(
            model_name='palet',
            name='sevkiyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paletler', to='finance.sevkiyat', verbose_name='Yüklendiği Tır'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='durum',
            field=models.CharField(choices=[('depoda', 'Depoda Bekliyor'), ('isleniyor', 'İşleniyor/Paketlemede'), ('yuklendi', 'Tıra Yüklendi'), ('sevk', 'Sevkiyatta/Yolda'), ('cikti', 'Teslim Edildi')], default='depoda', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='mustahsil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.mustahsil', verbose_name='Sahibi'),
        ),
        migrations.DeleteModel(
            name='Sevkiyat',
        ),
        migrations.DeleteModel(
            name='SevkiyatPaleti',
        ),
    ]
