# Generated by Django 5.2.12 on 2026-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_sevkiyatpaleti_sevkiyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palet',
            name='palet_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Palet ID / Barkod (Boş bırakılabilir)'),
        ),
    ]
