# Generated by Django 5.2.12 on 2026-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_palet_palet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='urun_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='palet_fotos/%Y/%m/%d/', verbose_name='Ürün Fotoğrafı (Kalite Kontrol)'),
        ),
    ]
