# Generated by Django 5.2.12 on 2026-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_palet_urun_fotografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='brut_miktar_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kantar Giriş (Brüt KG)'),
        ),
        migrations.AddField(
            model_name='palet',
            name='fire_miktar_kg',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='İşleme Farkı (Fire/Çıkma)'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='miktar_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paketlenen / Stok (Net KG)'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Toplam Tutar (Ödemeye Esas)'),
        ),
    ]
