# Generated by Django 5.2.12 on 2026-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_palet_brut_miktar_kg_palet_fire_miktar_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palet',
            name='durum',
            field=models.CharField(choices=[('depoda', 'Depoda Bekliyor'), ('isleniyor', 'İşleniyor/Paketlemede'), ('yuklendi', 'Tıra Yüklendi'), ('sevk', 'Sevkiyatta/Yolda'), ('cikti', 'Teslim Edildi')], default='isleniyor', max_length=20, verbose_name='Durum'),
        ),
    ]
