# Generated by Django 5.2.12 on 2026-04-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_palet_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palet',
            name='depo_konumu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.depo', verbose_name='Bulunduğu Oda'),
        ),
        migrations.AlterField(
            model_name='palet',
            name='miktar_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paketlenen / Stok (Net KG)'),
        ),
    ]
