# Generated by Django 5.2.12 on 2026-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_palet_depo_konumu_alter_palet_miktar_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='toplam_palet_adedi',
            field=models.PositiveIntegerField(default=1, help_text='Banttan çıkan toplam palet sayısı', verbose_name='Palet Adedi (İşleme Sonucu)'),
        ),
    ]
