# Generated by Django 5.2.12 on 2026-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_palet_toplam_palet_adedi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palet',
            name='toplam_palet_adedi',
            field=models.PositiveIntegerField(default=1, help_text='İşleme sonucu çıkan palet sayısı', verbose_name='Toplam Palet Adedi'),
        ),
    ]
