# Generated by Django 5.2.12 on 2026-04-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_palet_toplam_palet_adedi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palet',
            options={'ordering': ['-id'], 'verbose_name': 'Palet Takibi', 'verbose_name_plural': 'Depodaki Paletler'},
        ),
    ]
