# Generated by Django 5.2.12 on 2026-04-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yoklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('giris', 'Giriş Yaptı'), ('cikis', 'Çıkış Yaptı')], max_length=10, verbose_name='İşlem Tipi')),
                ('tarih_saat', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
        ),
    ]
