# Generated by Django 5.2.12 on 2026-04-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yoklama',
            options={'verbose_name': 'Yoklama', 'verbose_name_plural': 'Yoklama'},
        ),
    ]
