# Generated by Django 5.2.12 on 2026-04-05 19:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_yoklama_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelRapor',
            fields=[
            ],
            options={
                'verbose_name': 'Personel Mesai Raporu',
                'verbose_name_plural': '📊 Personel Mesai Raporları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.personel',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
